language: python
python:
  - "2.7"

before_install:
  - pip install -r requirements.txt

# command to install dependencies
install:
  - python generate_code.py -r 
  - python setup.py install

# command to run tests
script: python run_tests.py
