language: python
python:
  - "2.7"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - cp site.template.cfg site.cfg
  - python setup.py install

# command to run tests
script: python run_tests.py
